# Generated by Django 4.2 on 2023-04-13 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=5)),
                ('comment', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.IntegerField()),
                ('e_mail', models.EmailField(max_length=50)),
                ('phone', models.IntegerField()),
                ('city', models.CharField(max_length=5)),
                ('telegram_nickname', models.CharField(max_length=5)),
                ('youtrack_login', models.CharField(max_length=5)),
                ('edu_lvl', models.CharField(max_length=5)),
                ('edu_institut', models.CharField(max_length=5)),
                ('edu_spec', models.CharField(max_length=5)),
                ('resume_title', models.CharField(max_length=5)),
                ('cover_letter_text', models.CharField(max_length=5)),
                ('skills', models.CharField(max_length=5)),
                ('skills_detailed', models.CharField(max_length=5)),
                ('role', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='UserTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='interns.tags')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interns.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sum', models.IntegerField()),
                ('comment', models.CharField(max_length=100)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='interns.user')),
            ],
        ),
    ]
